# Generated by Django 4.2 on 2023-04-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=255)),
                ("email_address", models.CharField(max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.CharField(max_length=200)),
                ("smtp_username", models.CharField(max_length=255)),
                ("smtp_password", models.CharField(max_length=255)),
                ("imap_host", models.CharField(max_length=200)),
                ("imap_port", models.CharField(max_length=200)),
                ("imap_username", models.CharField(max_length=255)),
                ("imap_password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=100)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("scheduled_time", models.DateTimeField()),
                (
                    "connected_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.connectedemail",
                    ),
                ),
                ("leads", models.ManyToManyField(to="api.lead")),
            ],
        ),
    ]
